name: Python Unittests
on:
  pull_request: { }
  push: { branches: main }

jobs:
  test:
    name: Run python unittests in docker
    runs-on: ubuntu-latest
    container:
      image: jeffquinnmsk/bayestme:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: make python-unittest